export enum MatchPhase {
  INITIALIZING = "INITIALIZING", SHUFFLING = "SHUFFLING", DEALING = "DEALING",
  WAITING_FOR_SELECTION = "WAITING_FOR_SELECTION", CARD_SELECTED = "CARD_SELECTED",
  CARD_LOCKED = "CARD_LOCKED", WAITING_FOR_OPPONENT = "WAITING_FOR_OPPONENT",
  REVEALING = "REVEALING", RESOLVING = "RESOLVING", SHOWING_RESULT = "SHOWING_RESULT",
  DISCARDING = "DISCARDING", DRAWING = "DRAWING", MATCH_FINISHED = "MATCH_FINISHED", PAUSED = "PAUSED"
}
